server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: taskflow-backend
  data:
    mongodb:
      uri: mongodb://localhost:27017/taskflow
  security:
    jwt:
      secret: mySecretKey123456789012345678901234567890
      expiration: 86400000 # 24 hours
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: UTC

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    com.taskflow.backend: DEBUG
    org.springframework.security: DEBUG
